### ISSUE TITLE
Option to default image background style

### ISSUE THREAD

**Issue by docrinehart** [atom/image-view#57]
It would be nice to select a default image background rather than having to change it each time I want to view an image. I use really dark atom themes, and the sudden white background throws me off when I look at an image.

**Comment by lenovouser** [comment]
Would like to see this too!

**Comment by mefynn** [comment]
+1

**Comment by simurai** [comment]
With #117 the default background changed to **transparent**. Closing this as `wontfix`. We might can reconsider if somebody wants to look into continuing with #80.

**Comment by andb0t** [comment]
I have a dark background and the default transparent option hides all black image parts (in my case axis labels for plots - they are really important!). I now have to tediously change the background every time I want to investigate one of my pngs. I would really appreciate if there would be a memory option for the chosen setting as mentioned in PRs #80 and #75. Any chance we might get this?

**Comment by simurai** [comment]
@andb0t You can paste the following in your [styles.less](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks) file:

```less
// Image View: Show white background as default
.image-container:not([background]) {
  background-color: white;
  background-image: url(atom://image-view/images/transparent-background.png);
}
```

This should make it white again.
